### ISSUE TITLE
The question is about calling the main net api address.

### ISSUE THREAD

**Issue by choyoungsang** [virtualeconomy/cs-v-sdk#2]
When will this address be available?

If you are currently connected, the requested resource could not be found, but will be available again in the future. I get an error.
[https://wallet.v.systems/api]
Thank you.

**Comment by SheldonYS** [comment]
`https://wallet.v.systems/api` is the gate way of API, but you need to input the full API path, for example, `https://wallet.v.systems/api/blocks/height`. The swagger client for mainnet wallet is not open to public. If you want to use mainnet swagger, please use `http://13.55.174.115:9922` or you setup a full node in local.

**Comment by choyoungsang** [comment]
Thank you for quick response.

http://13.55.174.115:9922 Will continuous use be restricted by using the address?
Should I set the mainnet to local?

**Comment by SheldonYS** [comment]
No, http://13.55.174.115:9922 is only for temporary usage. For long term solution, you'd better setup a full node in local and call local node API.
